name: "Comprueba hitos"
on:
  pull_request:
    paths:
      - 'proyectos/hito-[1234567].md'

jobs:
  check_milestones:
    runs-on: ubuntu-latest
    steps:
      - name: Extrae URL del repositorio
        uses: JJ/github-pr-contains-action@releases/v2
        with:
          github-token: ${{github.token}}
          filesChanged: 1
      - name: Comprueba hitos
        uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const diff = process.env.diff;
            const ghRepoMatch = /github.com\/(\S+)\/(.+?)(:\s+|\))/.exec(diff)
            if  ( ghRepoMatch === null ) {
                core.setFailed("❌ There's no repo URL in this diff with required format")
            } else {
                const user = ghRepoMatch[1] // segundo resultado
                const repo = ghRepoMatch[2] // tercer resultado
                console.log( "» Trabajando con el repo " + repo + " para el usuario " + user )
                const milestones = await github.issues.listMilestones( { owner: user, repo: repo } )
                if ( ! milestones.data.length ) {
                    core.setFailed("❌ Tiene que haber por lo menos un milestone")
                }
                const minMilestones = 3
                if ( minMilestones && milestones.data.length < minMilestones ) {
                    core.setFailed( "❌ Tendría que haber más de " + minMilestones + " milestone(s)");
                }
                var totalIssues = 0
                var totalClosedIssues = 0
                milestones.data.forEach( async function( milestone ) {
                    totalIssues += milestone.open_issues + milestone.closed_issues
                    totalClosedIssues += milestone.closed_issues
                })
                console.log( "✅ Hay " + totalIssues + " issues en tus milestones y " + totalClosedIssues + " cerrados ")
                if ( ! totalIssues ) {
                    core.setFailed( "❌ No hay ningún issue en tus milestones")
                } else if ( ! totalClosedIssues ) {
                    core.setFailed( "❌ No hay ningún issue cerrado milestones")
                }
            }
