name: "Prueba del microservicio"
on:
  workflow_run:
    workflows: ["Nombre contenedor Docker"]
    paths:
      - 'proyectos/hito-[67].md'
    types: completed

jobs:
  docker_get:
    runs-on: ubuntu-latest
    steps:
      - name: Descarga valores usuario
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          workflow: extrae-usuario-repo.yaml
          workflow_conclusion: success
          name: user-repo
      - name: Crea variables de entorno
        run: |
          cat USER_REPO
          cat USER_REPO >> $GITHUB_ENV
      - name: Descarga valores contenedor
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          workflow: docker-container.yaml
          workflow_conclusion: success
          name: ${{env.IV_USER}}-iv-container
      - name: Crea variables de entorno para el contenedor
        run: |
          cat CONTAINER
          cat CONTAINER >> $GITHUB_ENV
      - name: Descarga valores configuraciÃ³n
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          workflow: sube-config.yaml
          workflow_conclusion: success
          name: ${{env.IV_USER}}-iv-config
      - name: Crea variables de entorno para el contenedor
        run: |
          cat IV_CONFIG
          cat IV_CONFIG >> $GITHUB_ENV
      - name: Descarga repo usuario y ejecuta contenedor
        uses: actions/checkout@v2
        with:
          repository: '${{env.IV_USER}}/${{env.IV_REPO}}'
      - name: Ejecuta test
        run: |
          docker run -t -v `pwd`:/test ${CONTAINER,,}  ${IV_ORDEN_TAREAS} build && ${IV_ORDEN_TAREAS} install && ${IV_ORDEN_TAREAS} test

