name: "Comprueba la existencia de historias de usuario"
on:
  pull_request:
    paths:
      - 'proyectos/hito-[1234567].md'

jobs:
  user_story_check:
    runs-on: ubuntu-latest
    steps:
      - name: Extrae URL del repositorio
        uses: JJ/github-pr-contains-action@releases/v1
        with:
          github-token: ${{github.token}}
          filesChanged: 1
      - name: Busca historias de usuario
        uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const diff = process.env.diff;
            const ghRepoMatch = /github.com\/(\S+)\/(.+?)(:\s+|\))/.exec(diff)
            console.log(ghRepoMatch)
            if  ( ghRepoMatch === null ) {
                core.setFailed("❌ There's no repo URL in this diff with required format")
            } else {
                const user = ghRepoMatch[1] // segundo resultado
                const repo = ghRepoMatch[2] // tercer resultado
                console.log( "» Retrieving repo " + repo + " for user " + user )
                const non_paginated_issues = await github.issues.listForRepo( {
                    owner: user,
                    repo: repo
                })
                const issues = await github.paginate( non_paginated_issues )
                console.log( issues )
                const user_stories = issues.filter( issue => issue.label == "user_stories" and issue.description.includes('HU') ) 
                if ( user_stories ) {
                    console.log( " ✅ Hay al menos una historia de usuario " )
                } else {
                    core.setFailed( " ❌ No hay ninguna historia de usuario en el repo " )
                }
          }

