name: "Comprueba la existencia de historias de usuario"
on:
  pull_request:
    paths:
      - 'proyectos/hito-[1234567].md'

jobs:
  user_story_check:
    runs-on: ubuntu-latest
    steps:
      - name: Extrae URL del repositorio
        uses: JJ/github-pr-contains-action@releases/v2
        with:
          github-token: ${{github.token}}
          filesChanged: 1
      - name: Busca historias de usuario
        uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const diff = process.env.diff;
            const ghRepoMatch = /github.com\/(\S+)\/(.+?)(:\s+|\))/.exec(diff)
            if  ( ghRepoMatch === null ) {
                core.setFailed("‚ùå No hay ning√∫n URL de un repositorio con el formato requerido en el diff")
            } else {
                const user = ghRepoMatch[1] // segundo resultado
                const repo = ghRepoMatch[2] // tercer resultado
                console.log( "¬ª Analizando repo " + repo + " del usuario üî•" + user )
                const non_paginated_issues = await github.issues.listForRepo.endpoint.merge( { owner: user, repo: repo })
                const issues = await github.paginate( non_paginated_issues )
                console.log( issues.filter( issue => issue.label != "" ) )
                console.log( issues.map( function( issue ) {
                    return issue.label
                })
                console.log( issues.filter( issue => issue.label === "user-stories" ) )
                const user_stories = issues.filter( issue => issue.label == "user-stories" && issue.description.includes('HU') )
                console.log( user_stories )
                if ( user_stories.length > 0 ) {
                    console.log( " ‚úÖ Hay al menos una historia de usuario " )
                } else {
                    core.setFailed( " ‚ùå No hay ninguna historia de usuario en el repo " )
                }
            }

